{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-10",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "43996156",
        "Fixer": "61599526"
    },
    "Package": {
        "Registry": "pip",
        "Name": "ray",
        "URL": "https://pypi.org/project/ray",
        "Downloads": "29176"
    },
    "CWEs": [
        {
            "ID": "CWE-94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "P",
        "AC": "H",
        "PR": "L",
        "UI": "N",
        "S": "U",
        "C": "L",
        "I": "L",
        "A": "L",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "3.8"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/ray-project/ray",
        "Codebase": [
            "Python"
        ],
        "Owner": "ray-project",
        "Name": "ray",
        "Forks": "2395",
        "Stars": "14840"
    },
    "Permalinks": [
        "https://user-images.githubusercontent.com/43996156/103398598-65669800-4b63-11eb-8386-0f62c5ce185f.png"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1505",
    "FixSubmissionCount": 1
}