{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-07",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": "61599526"
    },
    "Package": {
        "Registry": "pip",
        "Name": "archivy",
        "URL": "https://pypi.org/project/archivy",
        "Downloads": "48"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.3"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/archivy/archivy",
        "Codebase": [
            "Python"
        ],
        "Owner": "archivy",
        "Name": "archivy",
        "Forks": "50",
        "Stars": "1141"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1cNVR7tAAbzvVz_xCXgP2hGZ_bVjUDFHj/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1467",
    "FixSubmissionCount": 2
}