{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2020-12-24",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
      "Discloser": "B3EF",
      "Fixer": ""
    },
    "Package": {
      "Registry": "pip",
      "Name": "pydatalab",
      "URL": "https://github.com/googledatalab/pydatalab"
    },
    "CWEs": [
      {
        "ID": "94",
        "Description": "Arbitrary Code Execution"
      }
    ],
    "CVSS": {
      "Version": "3.1",
      "AV": "",
      "AC": "",
      "PR": "",
      "UI": "",
      "S": "",
      "C": "",
      "I": "",
      "A": "",
      "E": "",
      "RL": "",
      "RC": "",
      "Score": "8.5"
    },
    "CVEs": [""], 
    "Repository": {
      "URL": "https://github.com/googledatalab/pydatalab",
      "Codebase": ["PYTHON"],
      "Owner": "googledatalab",
      "Name": "pydatalab"
    },
    "Permalinks": ["https://github.com/googledatalab/pydatalab/blob/1d6865237fdc8d184123d1e89193578da56d73b3/google/datalab/utils/commands/_utils.py#L332"], 
    "References": [
      {
        "Description": "",
        "URL": ""
      }
    ]
  }
